### ISSUE TITLE
The problem has been solved.

### ISSUE THREAD

**Issue by onecatcute** [igoforth/RWAILib#2]
Problem solved. I have achieved the desired function. Thank you for your attention.This issue can be closed.
![游戏描述](https://github.com/user-attachments/assets/97231fbd-42c8-4ab7-b290-0ef9c5eaa724)
![存档描述](https://github.com/user-attachments/assets/e98fa287-5718-4c3a-8a1d-44829ae32dfe)

**Comment by igoforth** [comment]
Hi I still plan on looking into this. Could we reopen it?

**Comment by igoforth** [comment]
Do you still have your code?
